// AUTOGENERATED FILE
// This file was generated from dinosaur.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface ProgramActionDict<T> extends BaseActionDict<T> {
  command?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode, arg3: IterationNode, arg4: IterationNode) => T;
  drawToCommand?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  absoluteVerticalLineToCommand?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  absoluteVerticalLineToToken?: (this: NonterminalNode, arg0: TerminalNode) => T;
  relativeVerticalLineToCommand?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  relativeVerticalLineToToken?: (this: NonterminalNode, arg0: TerminalNode) => T;
  absoluteHorizontalLineToCommand?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  absoluteHorizontalLineToToken?: (this: NonterminalNode, arg0: TerminalNode) => T;
  relativeHorizontalLineToCommand?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  relativeHorizontalLineToToken?: (this: NonterminalNode, arg0: TerminalNode) => T;
  moveToCommand?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  moveToToken?: (this: NonterminalNode, arg0: TerminalNode) => T;
  coordinatePairSequence_recursive?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  coordinatePairSequence_single?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  coordinatePairSequence?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  coordinateSequence_recursive?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  coordinateSequence_single?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  coordinateSequence?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  coordinatePair?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  coordinate?: (this: NonterminalNode, arg0: IterationNode) => T;
  coordinateSeparator_space?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode) => T;
  coordinateSeparator_comma?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  coordinateSeparator?: (this: NonterminalNode, arg0: NonterminalNode) => T;
}

export interface ProgramSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: ProgramActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: ProgramActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: ProgramActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: ProgramActionDict<T>): this;
}

export interface ProgramGrammar extends Grammar {
  createSemantics(): ProgramSemantics;
  extendSemantics(superSemantics: ProgramSemantics): ProgramSemantics;
}

declare const grammar: ProgramGrammar;
export default grammar;

